language: php
php:
    - '7.2'
    - '7.3'
    - '7.4'

before_script:
    - composer install

script:
    - composer validate --strict
    - vendor/bin/phpcs src/

cache:
  directories:
    - $HOME/.composer/cache
